
import backend.SearchCustBills;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;
import javax.swing.plaf.basic.BasicPopupMenuUI;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Abhishek
 */
public class Suggestion extends javax.swing.JFrame {

    /**
     * Creates new form Suggestion
     */
    //Connection conn = null;
    
  
    DefaultListModel model = new DefaultListModel();
    
    public Suggestion() {
        initComponents();
        menu.add(jPanel1);
        menu.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicPopupMenuUI ui;
        ui = (BasicPopupMenuUI)menu.getUI();
    }
    
    
    
    private Connection databaseconnection(){
        Connection conn ;    
        try{
           String dbURL = "jdbc:mysql://localhost:3306/app_dev";
           String user = "root";
           String password = "#@Rahul8269";
           conn = DriverManager.getConnection(dbURL, user, password);
                    return conn;
        }catch (SQLException ex) {
            System.out.print(ex);
        }
        return null;
    }
    
           ArrayList arlist = new ArrayList();
          // String str = null;
        private ArrayList aList(){
           Connection conn = databaseconnection();
            try {
                String all;
//           String dbURL = "jdbc:mysql://localhost:3306/app_dev";
//           String user = "root";
//           String password = "#@Rahul8269";
//           conn = DriverManager.getConnection(dbURL, user, password);
            Statement st = conn.createStatement();
            String sql = "SELECT * FROM app_dev.cust_info";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                String nm = rs.getString("name");
                String id = rs.getString(1);
                String mobno = rs.getString(3);
                //if(mobno.isEmpty()){
                    String str= id+"    "+nm+"    "+mobno;
                    all=str;
                
                //else{
                  //  String str= id+"    "+nm+"      "+mobno;
                   // all=str;
                //}
                // str = rs.getString(1);
               arlist.add(all);
                model.addElement(all);
                System.out.println(all);
                
            }
            return arlist;
        } catch (SQLException ex) {
            Logger.getLogger(Suggestion.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
//        private String searchQuery(String search){
//        try {
//            Connection conn = databaseconnection();
//            String str = null;
//            Statement st = conn.createStatement();
//            String sql = "SELECT name FROM app_dev.cust_info where name like 'search%'";
//            ResultSet rs = st.executeQuery(sql);
//            while(rs.next()){
//                str=rs.getString(1);
//                System.out.println(str);
//            }
//            
//        } catch (SQLException ex) {
//            Logger.getLogger(Suggestion.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        return str;
//        }
        
        
    private void bindData(){
        aList().stream().forEach((arlist)->{
            model.addElement(arlist);
        } );
        list.setModel(model);
        list.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
    }
    
    private void searchFilter(String search){
        DefaultListModel filteredsearch = new DefaultListModel();
        ArrayList flist = aList();
        flist.stream().forEach((arlist)->{
            String listitem =arlist.toString().toLowerCase();
            if(listitem.contains(search.toLowerCase())){
                filteredsearch.addElement(arlist);
            }
        });
        model=filteredsearch ;
        list.setModel(model);
        arlist.removeAll(arlist); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        menu = new javax.swing.JPopupMenu();
        txt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(list);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKeyReleased(evt);
            }
        });

        table.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "MOB.NO.", "DATE", "BILL COPY"
            }
        ));
        table.setFocusable(false);
        table.setRowHeight(30);
        jScrollPane2.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
        public void search(String cid,String nm,String no){
        String custnm,custid,custno;
        
        //custnm =txt.getText();
        custid = cid;
        custnm = nm;
        custno = no;
        
        try {
           String dbURL = "jdbc:mysql://localhost:3306/app_dev";
           String user = "root";
           String password = "#@Rahul8269";
           Connection conn = null;
           
           conn = DriverManager.getConnection(dbURL, user, password);
           CallableStatement cscb = conn.prepareCall("{call search_customer_bills(?,?,?,?)}");
           
           cscb.setString(1, custid);
           cscb.setDate(4, null);
           cscb.setString(2, custnm);
           cscb.setString(3, custno);
           
           ResultSet rs = cscb.executeQuery();
           
           DefaultTableModel model = (DefaultTableModel) table.getModel();
           
           int rows = model.getRowCount();
           for(int i= rows-1;i>=0;i-- ){
               
               model.removeRow(i);
           }
            
            
            String id,name,mobno,date,billcpy;
            
            while(rs.next()){
                id = rs.getString(1);
                name = rs.getString(2);
                mobno = rs.getString(3);
                date= rs.getString(4);
                billcpy=rs.getString(5);
               String [] row ={id,name,mobno,date,billcpy}; 
                model.addRow(row);
            }
            
           
            
            conn.close();
            rs.close();
            cscb.close();
            
            
          
          
       } catch (SQLException ex) {
           Logger.getLogger(SearchCustBills.class.getName()).log(Level.SEVERE, null, ex);
       }
    }

    
    private void txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeyReleased
        String search  = txt.getText().trim();
        if(!search.equals("")){
            //System.out.println(search);
            menu.show(txt,0,txt.getHeight());
            searchFilter(txt.getText());
            //txt.setCursor();
            txt.requestFocus();
            //searchQuery(txt.getText());
            System.out.println(arlist);
        }
    }//GEN-LAST:event_txtKeyReleased

    private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
        String custinfo = list.getSelectedValue();
        
        int idlen= custinfo.indexOf(32);
        String idn = custinfo.substring(0, idlen);
       System.out.println(idn);
      
        int nmstrt=idlen+4;
        int nmend=custinfo.indexOf(32, nmstrt);

        String nmn= custinfo.substring(nmstrt, nmend);
        System.out.println(nmn);

        //String mobn = " ";
        int mobstrt=nmend+4;
        String mobn=custinfo.substring(mobstrt);
        System.out.println(mobn);
        
        search(idn,nmn,mobn);
        txt.setText(nmn);
        System.out.print(idn+" "+nmn+" "+mobn);
    }//GEN-LAST:event_listMouseClicked
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Suggestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Suggestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Suggestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Suggestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Suggestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> list;
    private javax.swing.JPopupMenu menu;
    private javax.swing.JTable table;
    private javax.swing.JTextField txt;
    // End of variables declaration//GEN-END:variables
}
