/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI;
import backend.AddNewRecord;
import backend.BillingInfo;
import backend.Check;
import backend.PdfSaveToDatabase;
import backend.SearchCustomerRecords;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.KeyEvent;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.plaf.basic.BasicPopupMenuUI;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfTemplate;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.PreparedStatement;


/**
 *
 * @author Abhishek
 */public class GenerateBillInF extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewIF
     */
    
    public void panelRefresh(){
        dateshow.setText("");
        idshowlbl.setText("");
        customernametxt.setText("");
        mobnotxt.setText("");
       
      
        DefaultTableModel model = (DefaultTableModel) table.getModel();
       
         int rows = model.getRowCount();
           for(int i= rows-1;i>=0;i-- ){
               
               model.removeRow(i);
           }
        
        dueamount.setText("");
        nettotalshowlbl.setText("");
        amountrec.setText("");
        descriptiontxt.setText("");  
        jCheckBox1.setSelected(false);
    }
    
    public GenerateBillInF() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        setuserdetails();
        
        menu.add(jPanel3);
        menu.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicPopupMenuUI mui;
        mui = (BasicPopupMenuUI)menu.getUI();
    }
    
    String id=null,date=null,name=null,loc =null;
    float ttl=0, amourec=0, rem=0;
    boolean nwusr=false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jDialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        canclelbl = new javax.swing.JLabel();
        oklbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        menu = new javax.swing.JPopupMenu();
        jDialog2 = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        printpnl = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        enterpriselbl = new javax.swing.JLabel();
        customernamelbl = new javax.swing.JLabel();
        datelbl = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        addresslbl = new javax.swing.JLabel();
        contactlbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        nettotalshowlbl = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        dateshow = new javax.swing.JLabel();
        nettotal = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        remainamount = new javax.swing.JLabel();
        dueamount = new javax.swing.JLabel();
        receivedamou = new javax.swing.JLabel();
        amountrec = new javax.swing.JTextField();
        customernametxt = new javax.swing.JTextField();
        descriptiontxt = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        mobilenolbl = new javax.swing.JLabel();
        mobnotxt = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        idlbl = new javax.swing.JLabel();
        idshowlbl = new javax.swing.JLabel();
        ownernamelbl = new javax.swing.JLabel();
        gstlbl = new javax.swing.JLabel();
        gstshowlbl = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        onwernameshowlbl = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        addrow = new javax.swing.JLabel();
        printlbl = new javax.swing.JLabel();
        deleterow = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        amountrec2 = new javax.swing.JTextField();
        amountrec3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jDialog1.setLocationByPlatform(true);
        jDialog1.setMinimumSize(new java.awt.Dimension(400, 300));
        jDialog1.setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Please confirm the print and save");

        canclelbl.setBackground(new java.awt.Color(255, 255, 255));
        canclelbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        canclelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        canclelbl.setText("cancle");
        canclelbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        canclelbl.setOpaque(true);
        canclelbl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                canclelblMouseMoved(evt);
            }
        });
        canclelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canclelblMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                canclelblMouseExited(evt);
            }
        });

        oklbl.setBackground(new java.awt.Color(255, 255, 255));
        oklbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        oklbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oklbl.setText("OK");
        oklbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        oklbl.setOpaque(true);
        oklbl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                oklblMouseMoved(evt);
            }
        });
        oklbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oklblMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                oklblMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(oklbl, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(canclelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oklbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canclelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(list);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jDialog2.setMinimumSize(new java.awt.Dimension(400, 300));
        jDialog2.setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setMaximumSize(new java.awt.Dimension(338, 247));
        jPanel4.setMinimumSize(new java.awt.Dimension(338, 247));
        jPanel4.setPreferredSize(new java.awt.Dimension(338, 247));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 153));
        jLabel12.setText("Empty Name !!!");
        jLabel12.setOpaque(true);

        jLabel13.setBackground(new java.awt.Color(0, 153, 153));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("      OK");
        jLabel13.setOpaque(true);
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel12)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1300, 850));
        setMinimumSize(new java.awt.Dimension(1300, 850));
        setPreferredSize(new java.awt.Dimension(1300, 850));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1300, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(1300, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        printpnl.setBackground(new java.awt.Color(255, 255, 255));
        printpnl.setMaximumSize(new java.awt.Dimension(920, 810));
        printpnl.setMinimumSize(new java.awt.Dimension(920, 810));
        printpnl.setPreferredSize(new java.awt.Dimension(920, 810));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setToolTipText("");
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        enterpriselbl.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        enterpriselbl.setText("Enterp. Name here");

        customernamelbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customernamelbl.setText("Customer Name :");

        datelbl.setText("DATE : ");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOpaque(true);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setToolTipText("");
        jSeparator3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        addresslbl.setText("address here ");

        contactlbl.setText("Contact details");

        table.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "desc", "quantity", "item wgt", "rate", "total"
            }
        ));
        table.setRowHeight(40);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setPreferredWidth(80);
            table.getColumnModel().getColumn(1).setPreferredWidth(10);
        }

        nettotalshowlbl.setBackground(new java.awt.Color(255, 255, 255));
        nettotalshowlbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nettotalshowlbl.setOpaque(true);

        jSeparator4.setBackground(new java.awt.Color(0, 153, 153));
        jSeparator4.setForeground(new java.awt.Color(0, 153, 153));
        jSeparator4.setOpaque(true);

        dateshow.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        nettotal.setBackground(new java.awt.Color(0, 153, 153));
        nettotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nettotal.setForeground(new java.awt.Color(255, 255, 255));
        nettotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nettotal.setText("NET TOTAL");
        nettotal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nettotal.setOpaque(true);
        nettotal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                nettotalMouseMoved(evt);
            }
        });
        nettotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nettotalMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nettotalMouseExited(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(0, 153, 153));
        jSeparator5.setForeground(new java.awt.Color(0, 153, 153));
        jSeparator5.setOpaque(true);

        remainamount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        remainamount.setText("Amount due :");

        dueamount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dueamount.setForeground(new java.awt.Color(255, 0, 0));

        receivedamou.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        receivedamou.setText("Amount Received :");

        amountrec.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        amountrec.setBorder(null);
        amountrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountrecActionPerformed(evt);
            }
        });
        amountrec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amountrecKeyReleased(evt);
            }
        });

        customernametxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        customernametxt.setBorder(null);
        customernametxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                customernametxtKeyReleased(evt);
            }
        });

        descriptiontxt.setBorder(null);
        descriptiontxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptiontxtActionPerformed(evt);
            }
        });
        descriptiontxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descriptiontxtKeyReleased(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(0, 153, 153));
        jSeparator6.setForeground(new java.awt.Color(0, 153, 153));
        jSeparator6.setOpaque(true);

        mobilenolbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mobilenolbl.setText("Mob. no. :");

        mobnotxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mobnotxt.setBorder(null);
        mobnotxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mobnotxtKeyReleased(evt);
            }
        });

        jSeparator7.setBackground(new java.awt.Color(0, 153, 153));
        jSeparator7.setForeground(new java.awt.Color(0, 153, 153));
        jSeparator7.setOpaque(true);

        idlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idlbl.setText(" ID:");

        idshowlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        ownernamelbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ownernamelbl.setText("owner -:");

        gstlbl.setText("GST no. :");

        gstshowlbl.setText("here");

        jLabel15.setText("Contact details -:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("signature :- ");

        javax.swing.GroupLayout printpnlLayout = new javax.swing.GroupLayout(printpnl);
        printpnl.setLayout(printpnlLayout);
        printpnlLayout.setHorizontalGroup(
            printpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(printpnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(printpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printpnlLayout.createSequentialGroup()
                        .addComponent(datelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateshow, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(242, 242, 242))
            .addGroup(printpnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(printpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(printpnlLayout.createSequentialGroup()
                        .addComponent(addresslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(contactlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printpnlLayout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(dueamount, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(printpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printpnlLayout.createSequentialGroup()
                                .addComponent(nettotal, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nettotalshowlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(332, 332, 332))
                            .addGroup(printpnlLayout.createSequentialGroup()
                                .addComponent(receivedamou)
                                .addGap(18, 18, 18)
                                .addGroup(printpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(amountrec, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(323, 323, 323))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printpnlLayout.createSequentialGroup()
                        .addComponent(idlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idshowlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(customernamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(printpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(customernametxt))
                        .addGap(18, 18, 18)
                        .addComponent(mobilenolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(printpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator7)
                            .addComponent(mobnotxt, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                        .addGap(208, 208, 208))))
            .addGroup(printpnlLayout.createSequentialGroup()
                .addGap(635, 635, 635)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(printpnlLayout.createSequentialGroup()
                .addGroup(printpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(printpnlLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(printpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(descriptiontxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(remainamount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(printpnlLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(printpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enterpriselbl, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(printpnlLayout.createSequentialGroup()
                                .addComponent(ownernamelbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(onwernameshowlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(272, 272, 272)
                                .addComponent(gstlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(gstshowlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(printpnlLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        printpnlLayout.setVerticalGroup(
            printpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printpnlLayout.createSequentialGroup()
                .addGroup(printpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(printpnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(printpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(datelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateshow, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(enterpriselbl, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(printpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(printpnlLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(printpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gstlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gstshowlbl)))
                    .addGroup(printpnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(printpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ownernamelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(onwernameshowlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(printpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addresslbl)
                    .addComponent(contactlbl)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(printpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(printpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(customernamelbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(printpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mobilenolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mobnotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(idlbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(idshowlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(printpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator5)
                    .addComponent(jSeparator7))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(printpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(printpnlLayout.createSequentialGroup()
                        .addGroup(printpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dueamount, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addGroup(printpnlLayout.createSequentialGroup()
                                .addComponent(remainamount, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descriptiontxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(printpnlLayout.createSequentialGroup()
                        .addGroup(printpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nettotalshowlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nettotal, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(printpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(receivedamou)
                            .addComponent(amountrec, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        jPanel1.add(printpnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 920, 900));

        addrow.setBackground(new java.awt.Color(0, 153, 153));
        addrow.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addrow.setForeground(new java.awt.Color(255, 255, 255));
        addrow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addrow.setText("ADD ROW");
        addrow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addrow.setOpaque(true);
        addrow.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                addrowMouseMoved(evt);
            }
        });
        addrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addrowMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addrowMouseExited(evt);
            }
        });
        jPanel1.add(addrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 300, 100, 50));

        printlbl.setBackground(new java.awt.Color(0, 153, 153));
        printlbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        printlbl.setForeground(new java.awt.Color(255, 255, 255));
        printlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        printlbl.setText("PRINT");
        printlbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        printlbl.setOpaque(true);
        printlbl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                printlblMouseMoved(evt);
            }
        });
        printlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printlblMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                printlblMouseExited(evt);
            }
        });
        jPanel1.add(printlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 440, 100, 40));

        deleterow.setBackground(new java.awt.Color(0, 153, 153));
        deleterow.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleterow.setForeground(new java.awt.Color(255, 255, 255));
        deleterow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleterow.setText("DELETE ROW");
        deleterow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleterow.setOpaque(true);
        deleterow.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                deleterowMouseMoved(evt);
            }
        });
        deleterow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleterowMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleterowMouseExited(evt);
            }
        });
        jPanel1.add(deleterow, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 370, 100, 50));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 51, 51));
        jCheckBox1.setText("check this box ");
        jCheckBox1.setBorder(null);
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 520, 120, 30));

        amountrec2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        amountrec2.setForeground(new java.awt.Color(255, 51, 51));
        amountrec2.setText("amount due record");
        amountrec2.setBorder(null);
        amountrec2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountrec2ActionPerformed(evt);
            }
        });
        amountrec2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amountrec2KeyReleased(evt);
            }
        });
        jPanel1.add(amountrec2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1029, 580, 130, 30));

        amountrec3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        amountrec3.setForeground(new java.awt.Color(255, 51, 51));
        amountrec3.setText("if you want to exclude");
        amountrec3.setBorder(null);
        amountrec3.setOpaque(true);
        amountrec3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountrec3ActionPerformed(evt);
            }
        });
        amountrec3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amountrec3KeyReleased(evt);
            }
        });
        jPanel1.add(amountrec3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1029, 550, -1, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("10");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, 30, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 30, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("2");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 30, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("3");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 30, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("4");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 30, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("5");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 30, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("6");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 30, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("7");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 30, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("8");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 30, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("9");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 1297, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your haabandling code here:
        
       // customernametxt.setText(jList1.getSelectedValue());
        
        
       
    }//GEN-LAST:event_jList1MouseClicked

    private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
        // TODO add your handling code here:
         String custinfo = list.getSelectedValue();
         // System.out.println(custinfo);
        
        SearchCustomerRecords ci = new SearchCustomerRecords();
        
       String []indci = ci.returncustinfo(custinfo);
       
       id=indci[0];
       name=indci[1];
       String mobno=indci[2];
       
        
      // System.out.println(id);
       //System.out.println(name);
       //System.out.println(mobno);
       
       idshowlbl.setText(id);
       customernametxt.setText(name);
       mobnotxt.setText(mobno);
    }//GEN-LAST:event_listMouseClicked

    private void canclelblMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canclelblMouseMoved
        canclelbl.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_canclelblMouseMoved

    private void canclelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canclelblMouseClicked
        // TODO add your handling code here:
        // jPanel1.add(editrecordpnl);
        jDialog1.dispose();
    }//GEN-LAST:event_canclelblMouseClicked

    private void canclelblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canclelblMouseExited
        canclelbl.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_canclelblMouseExited

    private void oklblMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oklblMouseMoved
        oklbl.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_oklblMouseMoved

    private void oklblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oklblMouseClicked
        
        if(nwusr){
            
            String nm = customernametxt.getText();
            String mob = mobnotxt.getText();
            AddNewRecord.registernewcust(id,nm,mob);
        }
        billing(id);
        BillingInfo.setdatetobill(id, date);
        
        printBill(printpnl);
        try {
            savePdf();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GenerateBillInF.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(jCheckBox1.isSelected()){

        }
        else if(rem==0)//to remove unnecessary amount records 
        {
            
        }
        else{
            
           String lastamoudue = fetchlastamountdue(id);
          
           if(lastamoudue == null){
               lastamoudue="0";
           }
           
           float remlast=Float.parseFloat(lastamoudue);
           
            System.out.println( remlast);
            
            
           float remfinal=rem+remlast;
           
          String descrptn = descriptiontxt.getText();
           BillingInfo.setamountrecordsvalues(id, date, ttl,  remfinal, amourec, descrptn );
        }
        
        PdfSaveToDatabase pdf = new PdfSaveToDatabase();
        
        pdf.savepdftodb(loc, date, id);
        jDialog1.dispose();
//        jPanel1.removeAll();
//        GenerateBillInF ginf = new GenerateBillInF();
//        //jPanel1.add(ginf);
//        ginf.setVisible(true);
//        ginf.revalidate();
        panelRefresh();
    }//GEN-LAST:event_oklblMouseClicked

    private void oklblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oklblMouseExited
         oklbl.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_oklblMouseExited

    private void amountrec3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountrec3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_amountrec3KeyReleased

    private void amountrec3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountrec3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountrec3ActionPerformed

    private void amountrec2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountrec2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_amountrec2KeyReleased

    private void amountrec2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountrec2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountrec2ActionPerformed

    private void deleterowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleterowMouseExited
        deleterow.setBackground(new java.awt.Color(0, 152, 152));
    }//GEN-LAST:event_deleterowMouseExited

    private void deleterowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleterowMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        // System.out.println(model.getRowCount());
        model.removeRow(model.getRowCount()-1);
    }//GEN-LAST:event_deleterowMouseClicked

    private void deleterowMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleterowMouseMoved
        deleterow.setBackground(new java.awt.Color(0, 102, 103));
    }//GEN-LAST:event_deleterowMouseMoved

    private void printlblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printlblMouseExited
        printlbl.setBackground(new java.awt.Color(0, 152, 152));
    }//GEN-LAST:event_printlblMouseExited

    private void printlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printlblMouseClicked
        
        if(id==null){
            
            jDialog2.setLocationRelativeTo(null);
            jDialog2.setVisible(true);
        }
        else{
            jDialog1.setLocationRelativeTo(null);
            jDialog1.setVisible(true);   
        }
      

    }//GEN-LAST:event_printlblMouseClicked

    private void printlblMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printlblMouseMoved
        printlbl.setBackground(new java.awt.Color(0, 102, 103));
    }//GEN-LAST:event_printlblMouseMoved

    private void addrowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addrowMouseExited
        addrow.setBackground(new java.awt.Color(0, 152, 152));
    }//GEN-LAST:event_addrowMouseExited

    private void addrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addrowMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        if(model.getRowCount()<10){
            model.insertRow(model.getRowCount(), new Object[]{"","","","",""});
        }

    }//GEN-LAST:event_addrowMouseClicked

    private void addrowMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addrowMouseMoved
        addrow.setBackground(new java.awt.Color(0, 102, 103));
    }//GEN-LAST:event_addrowMouseMoved

    private void mobnotxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobnotxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_mobnotxtKeyReleased

    private void descriptiontxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descriptiontxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptiontxtKeyReleased

    private void descriptiontxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptiontxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptiontxtActionPerformed

    private void customernametxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customernametxtKeyReleased
        DefaultListModel model = new DefaultListModel();
        String search  = customernametxt.getText().trim();
        Suggestion suggestion = new Suggestion(list,model);
        if(!search.equals("")){
            menu.show(customernametxt,0,customernametxt.getHeight()+12);
            model = suggestion.searchFilter(customernametxt.getText());
            
            nwusr=false;
            
            if(model.isEmpty()){
                
                 int nwid = BillingInfo.getnewid();
                 id=Integer.toString(nwid);
                 idshowlbl.setText(id);
                
                 nwusr=true;
            }
            customernametxt.requestFocus();
        }
    }//GEN-LAST:event_customernametxtKeyReleased

    private void amountrecKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountrecKeyReleased
        // TODO add your handling code here:
        String total = nettotalshowlbl.getText();
        
        boolean ch = Check.onlyDigits(total, total.length());
        
        if(ch==true){
            ttl=Float.valueOf(total);

        String rec= amountrec.getText();
        if(rec==null){
            rec="0";
        }
        amourec=Float.valueOf(rec);

        rem=ttl-amourec;
        if(rem>=0){
        String remain=Float.toString(rem);
        dueamount.setText(remain);
        }
        else{
            dueamount.setText("NA");
        }
        }
        else{
            dueamount.setText("NA");
        }
        
        

    }//GEN-LAST:event_amountrecKeyReleased

    private void amountrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountrecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountrecActionPerformed

    private void nettotalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nettotalMouseExited
        nettotal.setBackground(new java.awt.Color(0, 152, 152));
    }//GEN-LAST:event_nettotalMouseExited

    private void nettotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nettotalMouseClicked
        // TODO add your handling code here:
        table.selectAll();
        float totalb=0;
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int rows= 0;
        rows=model.getRowCount();

               for(int i=0;i<rows;i++){

            float a = Float.parseFloat(model.getValueAt(i, 4).toString());

           // System.out.println(a);
            totalb=totalb+a;
           // System.out.println(totalb);

        }

        nettotalshowlbl.setText(Float.toString(totalb));
    }//GEN-LAST:event_nettotalMouseClicked

    private void nettotalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nettotalMouseMoved
        nettotal.setBackground(new java.awt.Color(0, 102, 103));
    }//GEN-LAST:event_nettotalMouseMoved

    private void tableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_tableKeyReleased

    private void tableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKeyPressed
        // for creating new rows

        DefaultTableModel model = (DefaultTableModel) table.getModel();
        if(evt.getKeyCode()==KeyEvent.VK_INSERT){
            int selectedrow = table.getSelectedRow()+1;

            int rowcount = model.getRowCount();

            if((selectedrow== rowcount) &&
                (rowcount<10)){
                model.insertRow(model.getRowCount(), new Object[]{"","","","",""});

            }

        }
    }//GEN-LAST:event_tableKeyPressed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tableMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        jDialog2.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    
    private void printBill(JPanel panel){
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        printerJob.setJobName("print bill");
        printerJob.setPrintable(new Printable() {
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
               if(pageIndex>0){
                   return Printable.NO_SUCH_PAGE;
               }
               Graphics2D graphics2D = (Graphics2D)graphics;
               graphics2D.translate(pageFormat.getImageableX()*2,pageFormat.getImageableY()*2);
               graphics2D.scale(0.769,1.0 );
               panel.paint(graphics2D);
               return Printable.PAGE_EXISTS;
            }
        });
        boolean returningResult = printerJob.printDialog();
            if(returningResult){
                try{
                    printerJob.print();
                }catch(PrinterException printerex){
                    JOptionPane.showMessageDialog(this,"Print error: "+printerex.getMessage());
                }
            }
    }
    
    private void billing(String id){
        
        String des=null;
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            table.selectAll();
            
            
             LocalDateTime bd = LocalDateTime.now();
              date = bd.toString();
        try {
            
            String dbURL = "jdbc:mysql://localhost:3306/app_dev";
            String user = "root";
            String password = "#@Rahul8269";
            Connection conn = null;
            conn = DriverManager.getConnection(dbURL, user, password);
            CallableStatement cbi = conn.prepareCall("call billing_info (?,?,?,?,?,?,?)");
           int rows=model.getRowCount();
            for(int i=0; i<rows;i++){
                
                System.out.print(rows);
                des=String.valueOf(model.getValueAt(i, 0));
               int quantity=Integer.parseInt(model.getValueAt(i, 1).toString());
               float itmweight=Float.parseFloat(model.getValueAt(i, 2).toString());
               float rate=Float.parseFloat(model.getValueAt(i, 3).toString());
               float total=Float.parseFloat(model.getValueAt(i, 4).toString());
                
                
                cbi.setString(1,id );//id
                cbi.setString(2,date);//date
                cbi.setString(3, des);//dscription
                cbi.setFloat(4,quantity);//quantity
                cbi.setFloat(5, itmweight);//weight
                cbi.setFloat(6, rate);//rate
                cbi.setFloat(7, total);//total
                
              cbi.execute();
                
            }
            
            conn.close();
        } catch (SQLException ex) {
           // jDialog1.setVisible(true);
            Logger.getLogger(GenerateBillInF.class.getName()).log(Level.SEVERE, null, ex);
            
        }
    }
    
    private void setuserdetails(){
        
        
             String mobno = null,enterprisename = null,gstno,enterpriseadd = null;
            LocalDateTime bd = LocalDateTime.now();
            DateTimeFormatter format = DateTimeFormatter.ofPattern("dd-mm-yyyy");
            String datef = bd.format(format);
            dateshow.setText(datef);
        try {
            
            String dbURL = "jdbc:mysql://localhost:3306/app_dev";
            String user = "root";
            String password = "#@Rahul8269";
            Connection conn = null;
            conn = DriverManager.getConnection(dbURL, user, password);
            Statement st = conn.createStatement();
            String sql = "select name,mob_no,enterprise_name,gstno,enterprise_address from user_registration ";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                name = rs.getString(1);
                mobno = rs.getString(2);
                enterprisename= rs.getString(3);
                gstno= rs.getString(4);
                enterpriseadd= rs.getString(5);
            }
            
            enterpriselbl.setText( enterprisename);
            addresslbl.setText(enterpriseadd);
            contactlbl.setText( mobno);
            
        } catch (SQLException ex) {
            Logger.getLogger(GenerateBillInF.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    
    }
    
    public void savePdf() throws FileNotFoundException{
        Document doc = new Document(PageSize.A3);
        DateTimeFormatter format = DateTimeFormatter.ofPattern("dd-mm-yyyy_hh-mm-ss");
        LocalDateTime bd = LocalDateTime.now();
       String datef = bd.format(format);
        loc = "C://Account_management//bills//"+id+name+datef+".pdf";
        try {            
            try {
                PdfWriter writer = PdfWriter.getInstance(doc,new FileOutputStream(loc));
                doc.open();
                PdfContentByte contentbyte = writer.getDirectContent();
                PdfTemplate template = contentbyte.createTemplate(800, 810);
                Graphics2D g2 = template.createGraphics(800, 810);
                printpnl.print(g2);
                g2.dispose();
               contentbyte.addTemplate(template, 0,300);
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(GenerateBillInF.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (DocumentException ex) {
            Logger.getLogger(GenerateBillInF.class.getName()).log(Level.SEVERE, null, ex);
        }
        doc.close();
    }
    
    private String fetchlastamountdue(String id ){
         
        String due=null;
        try {
           
            
            String dbURL = "jdbc:mysql://localhost:3306/app_dev";
            String user = "root";
            String password = "#@Rahul8269";
            Connection conn = null;
            conn = DriverManager.getConnection(dbURL, user, password);
            
            String sql ="select amount_due from amount_records where id=? order by trnx_date desc;";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, id);
            
            ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
                due =rs.getString(1);
            }
            
           
        } catch (SQLException ex) {
            Logger.getLogger(GenerateBillInF.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         return due ;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addresslbl;
    private javax.swing.JLabel addrow;
    private javax.swing.JTextField amountrec;
    private javax.swing.JTextField amountrec2;
    private javax.swing.JTextField amountrec3;
    private javax.swing.JLabel canclelbl;
    private javax.swing.JLabel contactlbl;
    private javax.swing.JLabel customernamelbl;
    private javax.swing.JTextField customernametxt;
    private javax.swing.JLabel datelbl;
    private javax.swing.JLabel dateshow;
    private javax.swing.JLabel deleterow;
    private javax.swing.JTextField descriptiontxt;
    private javax.swing.JLabel dueamount;
    private javax.swing.JLabel enterpriselbl;
    private javax.swing.JLabel gstlbl;
    private javax.swing.JLabel gstshowlbl;
    private javax.swing.JLabel idlbl;
    private javax.swing.JLabel idshowlbl;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JList<String> list;
    private javax.swing.JPopupMenu menu;
    private javax.swing.JLabel mobilenolbl;
    private javax.swing.JTextField mobnotxt;
    private javax.swing.JLabel nettotal;
    private javax.swing.JLabel nettotalshowlbl;
    private javax.swing.JLabel oklbl;
    private javax.swing.JLabel onwernameshowlbl;
    private javax.swing.JLabel ownernamelbl;
    private javax.swing.JLabel printlbl;
    private javax.swing.JPanel printpnl;
    private javax.swing.JLabel receivedamou;
    private javax.swing.JLabel remainamount;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
