/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseEvent;
/**
 *
 * @author Abhishek
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    int cornerRadius;
    Color backgroundColor;
    
    public MainFrame() {
        initComponents();
        
        SearchInF sif = new SearchInF();
        basepanel.removeAll();
        basepanel.add(sif).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        dashboardpanel = new javax.swing.JPanel();
        welcomelbl = new javax.swing.JLabel();
        menuinfo = new javax.swing.JLabel();
        homelbl = new javax.swing.JLabel();
        genbilllbl = new javax.swing.JLabel();
        billinghislbl = new javax.swing.JLabel();
        addreclbl = new javax.swing.JLabel();
        importreclbl = new javax.swing.JLabel();
        basepanel = new javax.swing.JPanel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1676, 850));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboardpanel.setBackground(new java.awt.Color(0, 153, 153));
        dashboardpanel.setMaximumSize(new java.awt.Dimension(360, 346));
        dashboardpanel.setMinimumSize(new java.awt.Dimension(360, 346));
        dashboardpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomelbl.setForeground(new java.awt.Color(255, 255, 255));
        welcomelbl.setText("WELCOME......");
        dashboardpanel.add(welcomelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 30));

        menuinfo.setBackground(new java.awt.Color(0, 102, 102));
        menuinfo.setForeground(new java.awt.Color(255, 255, 255));
        menuinfo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        menuinfo.setText("SEARCH CUSTOMER   ");
        menuinfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuinfo.setOpaque(true);
        dashboardpanel.add(menuinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 370, 60));

        homelbl.setBackground(new java.awt.Color(0, 153, 153));
        homelbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        homelbl.setForeground(new java.awt.Color(255, 255, 255));
        homelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homelbl.setText("HOME");
        homelbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homelbl.setOpaque(true);
        homelbl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                homelblMouseMoved(evt);
            }
        });
        homelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homelblMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homelblMousePressed(evt);
            }
        });
        dashboardpanel.add(homelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 370, 50));

        genbilllbl.setBackground(new java.awt.Color(0, 153, 153));
        genbilllbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        genbilllbl.setForeground(new java.awt.Color(255, 255, 255));
        genbilllbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        genbilllbl.setText("GENERATE BILL");
        genbilllbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        genbilllbl.setOpaque(true);
        genbilllbl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                genbilllblMouseMoved(evt);
            }
        });
        genbilllbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                genbilllblMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                genbilllblMouseExited(evt);
            }
        });
        dashboardpanel.add(genbilllbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 370, 50));

        billinghislbl.setBackground(new java.awt.Color(0, 153, 153));
        billinghislbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        billinghislbl.setForeground(new java.awt.Color(255, 255, 255));
        billinghislbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        billinghislbl.setText("BILLING HISTORY");
        billinghislbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        billinghislbl.setOpaque(true);
        billinghislbl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                billinghislblMouseMoved(evt);
            }
        });
        billinghislbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                billinghislblMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                billinghislblMousePressed(evt);
            }
        });
        dashboardpanel.add(billinghislbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 370, 50));

        addreclbl.setBackground(new java.awt.Color(0, 153, 153));
        addreclbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addreclbl.setForeground(new java.awt.Color(255, 255, 255));
        addreclbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addreclbl.setText("ADD NEW RECORD");
        addreclbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addreclbl.setOpaque(true);
        addreclbl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                addreclblMouseMoved(evt);
            }
        });
        addreclbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addreclblMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addreclblMousePressed(evt);
            }
        });
        dashboardpanel.add(addreclbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 370, 50));

        importreclbl.setBackground(new java.awt.Color(0, 153, 153));
        importreclbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        importreclbl.setForeground(new java.awt.Color(255, 255, 255));
        importreclbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        importreclbl.setText("Import Records");
        importreclbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        importreclbl.setOpaque(true);
        importreclbl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                importreclblMouseMoved(evt);
            }
        });
        importreclbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                importreclblMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                importreclblMousePressed(evt);
            }
        });
        dashboardpanel.add(importreclbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 354, 29));

        getContentPane().add(dashboardpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 369, 850));

        basepanel.setBackground(new java.awt.Color(255, 255, 255));
        basepanel.setMaximumSize(new java.awt.Dimension(1300, 850));
        basepanel.setMinimumSize(new java.awt.Dimension(1300, 850));
        basepanel.setPreferredSize(new java.awt.Dimension(1300, 850));

        javax.swing.GroupLayout basepanelLayout = new javax.swing.GroupLayout(basepanel);
        basepanel.setLayout(basepanelLayout);
        basepanelLayout.setHorizontalGroup(
            basepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
        );
        basepanelLayout.setVerticalGroup(
            basepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );

        getContentPane().add(basepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 1, 1300, 850));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homelblMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelblMouseMoved
        homelbl.setBackground(new java.awt.Color(0, 102, 103));
    }//GEN-LAST:event_homelblMouseMoved

    private void homelblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelblMouseExited
       homelbl.setBackground(new java.awt.Color(0, 152, 152));
    }//GEN-LAST:event_homelblMouseExited

    private void billinghislblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billinghislblMouseExited
        billinghislbl.setBackground(new java.awt.Color(0, 152, 152));
    }//GEN-LAST:event_billinghislblMouseExited

    private void billinghislblMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billinghislblMouseMoved
        billinghislbl.setBackground(new java.awt.Color(0, 102, 103));
    }//GEN-LAST:event_billinghislblMouseMoved

    private void genbilllblMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genbilllblMouseMoved
        genbilllbl.setBackground(new java.awt.Color(0, 102, 103));
    }//GEN-LAST:event_genbilllblMouseMoved

    private void genbilllblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genbilllblMouseExited
        genbilllbl.setBackground(new java.awt.Color(0, 152, 152));
    }//GEN-LAST:event_genbilllblMouseExited

    private void addreclblMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addreclblMouseMoved
        addreclbl.setBackground(new java.awt.Color(0, 102, 103));
    }//GEN-LAST:event_addreclblMouseMoved

    private void addreclblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addreclblMouseExited
        addreclbl.setBackground(new java.awt.Color(0, 152, 152));
    }//GEN-LAST:event_addreclblMouseExited

    private void importreclblMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importreclblMouseMoved
        importreclbl.setBackground(new java.awt.Color(0, 102, 103));
    }//GEN-LAST:event_importreclblMouseMoved

    private void importreclblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importreclblMouseExited
        importreclbl.setBackground(new java.awt.Color(0, 152, 152));
    }//GEN-LAST:event_importreclblMouseExited

    private void genbilllblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genbilllblMouseClicked
        GenerateBillInF inf = new GenerateBillInF();
        basepanel.removeAll();
        basepanel.add(inf).setVisible(true);
        menuinfo.setText("GENERATE BILLS  ");
    }//GEN-LAST:event_genbilllblMouseClicked

    private void homelblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelblMousePressed
        SearchInF sif = new SearchInF();
        basepanel.removeAll();
        basepanel.add(sif).setVisible(true);
        menuinfo.setText("SEARCH CUSTOMER  ");
    }//GEN-LAST:event_homelblMousePressed

    private void billinghislblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billinghislblMousePressed
        BillingHistoryInF bif = new BillingHistoryInF(); 
        basepanel.removeAll();
        basepanel.add(bif).setVisible(true);
        menuinfo.setText("BILLING HISTORY  ");
    }//GEN-LAST:event_billinghislblMousePressed

    private void addreclblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addreclblMousePressed
        AddRecInF aif = new AddRecInF(); 
        basepanel.removeAll();
        basepanel.add(aif).setVisible(true);
        menuinfo.setText("ADD NEW RECORDS  ");
    }//GEN-LAST:event_addreclblMousePressed

    private void importreclblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importreclblMousePressed
        ImportRecInF iif = new ImportRecInF(); 
        basepanel.removeAll();
        basepanel.add(iif).setVisible(true);
        menuinfo.setText("Import/Export records  ");
    }//GEN-LAST:event_importreclblMousePressed

    
//        public void RoundedPanel(int radius) {
//            super();
//            cornerRadius = radius;
//        }
//
//        public void RoundedPanel(int radius, Color bgColor) {
//            super();
//            cornerRadius = radius;
//            backgroundColor = bgColor;
//        }
    /**
     *
     * @param g
     */
    @Override
    public void paintComponents(Graphics g){
    super.paintComponents(g);
    Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
        SearchInF sif = new SearchInF();
        //basepanel.removeAll();
        basepanel.add(sif).setVisible(true);
        
    };
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addreclbl;
    private static javax.swing.JPanel basepanel;
    private javax.swing.JLabel billinghislbl;
    private javax.swing.JPanel dashboardpanel;
    private javax.swing.JLabel genbilllbl;
    private javax.swing.JLabel homelbl;
    private javax.swing.JLabel importreclbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel menuinfo;
    private javax.swing.JLabel welcomelbl;
    // End of variables declaration//GEN-END:variables
}
