/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Abhishek
 */
public class RegistrationFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationFrame
     */
    
    String usrnm , phno,entnm,email,add,gstno,pass,confpass;
    public RegistrationFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        usernamelbl = new javax.swing.JLabel();
        enterpriselnamebl = new javax.swing.JLabel();
        phonenolbl = new javax.swing.JLabel();
        emaillbl = new javax.swing.JLabel();
        addresslbl = new javax.swing.JLabel();
        passwordlbl = new javax.swing.JLabel();
        gstnolbl = new javax.swing.JLabel();
        conpasswordlbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addresstxt = new javax.swing.JTextArea();
        usernametxt = new javax.swing.JTextField();
        phonenotxt = new javax.swing.JTextField();
        enterprisenametxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        gstnotxt = new javax.swing.JTextField();
        passwordtxt = new javax.swing.JTextField();
        conpasswordtxt = new javax.swing.JTextField();
        passworderror = new javax.swing.JLabel();
        savelbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        usernamelbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usernamelbl.setForeground(new java.awt.Color(255, 255, 255));
        usernamelbl.setText("Username : ");

        enterpriselnamebl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        enterpriselnamebl.setForeground(new java.awt.Color(255, 255, 255));
        enterpriselnamebl.setText("Enterprise name :");

        phonenolbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        phonenolbl.setForeground(new java.awt.Color(255, 255, 255));
        phonenolbl.setText("Phone number :");

        emaillbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emaillbl.setForeground(new java.awt.Color(255, 255, 255));
        emaillbl.setText("E-mail :");

        addresslbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addresslbl.setForeground(new java.awt.Color(255, 255, 255));
        addresslbl.setText("Address :");

        passwordlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passwordlbl.setForeground(new java.awt.Color(255, 255, 255));
        passwordlbl.setText("Password : ");

        gstnolbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gstnolbl.setForeground(new java.awt.Color(255, 255, 255));
        gstnolbl.setText("GST number : ");

        conpasswordlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        conpasswordlbl.setForeground(new java.awt.Color(255, 255, 255));
        conpasswordlbl.setText("Confirm Password :");

        addresstxt.setColumns(20);
        addresstxt.setRows(5);
        addresstxt.setBorder(null);
        jScrollPane1.setViewportView(addresstxt);

        usernametxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        usernametxt.setForeground(new java.awt.Color(0, 153, 153));
        usernametxt.setBorder(null);
        usernametxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernametxt.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        usernametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametxtActionPerformed(evt);
            }
        });

        phonenotxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        phonenotxt.setForeground(new java.awt.Color(0, 153, 153));
        phonenotxt.setBorder(null);
        phonenotxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        phonenotxt.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        phonenotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenotxtActionPerformed(evt);
            }
        });

        enterprisenametxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        enterprisenametxt.setForeground(new java.awt.Color(0, 153, 153));
        enterprisenametxt.setBorder(null);
        enterprisenametxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        enterprisenametxt.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        enterprisenametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterprisenametxtActionPerformed(evt);
            }
        });

        emailtxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emailtxt.setForeground(new java.awt.Color(0, 153, 153));
        emailtxt.setBorder(null);
        emailtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emailtxt.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        emailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtxtActionPerformed(evt);
            }
        });

        gstnotxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        gstnotxt.setForeground(new java.awt.Color(0, 153, 153));
        gstnotxt.setBorder(null);
        gstnotxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        gstnotxt.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        gstnotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gstnotxtActionPerformed(evt);
            }
        });

        passwordtxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passwordtxt.setForeground(new java.awt.Color(0, 153, 153));
        passwordtxt.setBorder(null);
        passwordtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        passwordtxt.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        passwordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordtxtActionPerformed(evt);
            }
        });

        conpasswordtxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        conpasswordtxt.setForeground(new java.awt.Color(0, 153, 153));
        conpasswordtxt.setBorder(null);
        conpasswordtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        conpasswordtxt.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        conpasswordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conpasswordtxtActionPerformed(evt);
            }
        });

        passworderror.setBackground(new java.awt.Color(0, 153, 153));
        passworderror.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        passworderror.setForeground(new java.awt.Color(255, 0, 0));
        passworderror.setText("hhell");
        passworderror.setOpaque(true);

        savelbl.setBackground(new java.awt.Color(255, 255, 255));
        savelbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        savelbl.setForeground(new java.awt.Color(0, 153, 153));
        savelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        savelbl.setText("SAVE");
        savelbl.setOpaque(true);
        savelbl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                savelblMouseMoved(evt);
            }
        });
        savelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                savelblMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                savelblMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enterpriselnamebl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emaillbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addresslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addComponent(enterprisenametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(82, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(savelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(gstnolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(gstnotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(phonenolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(phonenotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(usernamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(conpasswordlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(passworderror, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(conpasswordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernamelbl)
                    .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phonenolbl)
                    .addComponent(phonenotxt, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriselnamebl)
                    .addComponent(enterprisenametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emaillbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gstnotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gstnolbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addresslbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordlbl)
                    .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conpasswordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conpasswordlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passworderror, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(savelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 570, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametxtActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_usernametxtActionPerformed

    private void passwordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordtxtActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_passwordtxtActionPerformed

    private void phonenotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenotxtActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_phonenotxtActionPerformed

    private void emailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtxtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_emailtxtActionPerformed

    private void gstnotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gstnotxtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_gstnotxtActionPerformed

    private void conpasswordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conpasswordtxtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_conpasswordtxtActionPerformed

    private void enterprisenametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterprisenametxtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_enterprisenametxtActionPerformed

    private void savelblMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savelblMouseMoved
        savelbl.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_savelblMouseMoved

    private void savelblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savelblMouseExited
        savelbl.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_savelblMouseExited

    private void savelblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savelblMousePressed

    }//GEN-LAST:event_savelblMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addresslbl;
    private javax.swing.JTextArea addresstxt;
    private javax.swing.JLabel conpasswordlbl;
    private javax.swing.JTextField conpasswordtxt;
    private javax.swing.JLabel emaillbl;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JLabel enterpriselnamebl;
    private javax.swing.JTextField enterprisenametxt;
    private javax.swing.JLabel gstnolbl;
    private javax.swing.JTextField gstnotxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel passworderror;
    private javax.swing.JLabel passwordlbl;
    private javax.swing.JTextField passwordtxt;
    private javax.swing.JLabel phonenolbl;
    private javax.swing.JTextField phonenotxt;
    private javax.swing.JLabel savelbl;
    private javax.swing.JLabel usernamelbl;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables
}
